# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.

# [TEMPLATE] Compile C++ library Microsoft.MixedReality.WebRTC.Native.dll

parameters:
  buildAgent: ''
  buildPlatform: ''    # Win32|UWP
  buildArch: ''        # x86|x64|ARM|ARM64
  msbuildPlatform: ''  # Win32|x64|ARM|ARM64
  buildConfig: ''      # Debug|Release
 
jobs:

# Compile Microsoft.MixedReality.WebRTC.Native.dll
- job: cpp_${{parameters.buildPlatform}}_${{parameters.buildArch}}_${{parameters.buildConfig}}
  timeoutInMinutes: 360
  pool:
    name: ${{parameters.buildAgent}}
    demands: msbuild
  variables:
  - group: MixedReality-WebRTC-ArtifactConfig
  - name: buildTriple
    value: ${{parameters.buildPlatform}}-${{parameters.buildArch}}-${{parameters.buildConfig}}
  steps:
  - checkout: self
    submodules: recursive

  # Use NuGet 5.2.0
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.2.0'
    inputs:
      versionSpec: 5.2.0

  # Restore the NuGet packages containing the input dependencies
  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      command: restore
      restoreSolution: '$(Build.SourcesDirectory)/libs/Microsoft.MixedReality.WebRTC.Native/src/${{parameters.buildPlatform}}/packages.config'
      restoreDirectory: '$(Build.SourcesDirectory)/packages'
      includeNuGetOrg: true
      feedsToUse: config
      nugetConfigPath: '$(NuGetConfigPath)'
    timeoutInMinutes: 30

  # Ensure that Python 2.7.16 is the default; the Google scripts don't work with Python 3.x
  - task: UsePythonVersion@0
    displayName: 'Use Python 2.7.16 x64 for Google GN'
    inputs:
      versionSpec: 2.7.16
    timeoutInMinutes: 5

  # Map build* variables to script* ones
  - task: PowerShell@2
    displayName: Map script variables
    inputs:
      targetType: filePath
      filePath: tools/ci/mapVariables.ps1
      arguments: '${{parameters.buildPlatform}} ${{parameters.buildArch}} ${{parameters.buildConfig}}'

  # Prepare the environment with the setup script from Google
  - task: PythonScript@0
    displayName: Prepare WebRTC env
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a prepare -p $(scriptPlatform) --cpus $(scriptArch) -c $(scriptConfig)'
    timeoutInMinutes: 10

  # Build Microsoft.MixedReality.WebRTC.Native.dll
  - task: MSBuild@1
    displayName: 'Build C++ WebRTC lib ($(buildTriple))'
    inputs:
      solution: libs/Microsoft.MixedReality.WebRTC.Native/src/${{parameters.buildPlatform}}/Microsoft.MixedReality.WebRTC.Native.${{parameters.buildPlatform}}.vcxproj
      msbuildVersion: 15.0
      msbuildArchitecture: x64
      platform: ${{parameters.msbuildPlatform}}
      configuration: ${{parameters.buildConfig}}
    timeoutInMinutes: 20

  # Publish Microsoft.MixedReality.WebRTC.Native.dll and associated files (PDB, ...)
  - task: PublishPipelineArtifact@0
    displayName: 'Publish C++ WebRTC lib ($(buildTriple))'
    inputs:
      artifactName: 'Microsoft.MixedReality.WebRTC.Native_$(buildTriple)'
      targetPath: bin/${{parameters.buildPlatform}}/${{parameters.buildArch}}/${{parameters.buildConfig}}
